[tool.poetry]
name = "pokeai"
version = "0.1.0"
description = "Pokémon Showdown RL agent"
authors = ["Andrea Marzella <anmastdev@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
poke-env = ">=0.8"
wandb = "^0.26.0"
python-dotenv = "^1.2.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
jupyter = "^1.0"
ipykernel = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
